### ISSUE TITLE
Training for transfer learning

### ISSUE THREAD

**Issue by Bala93** [locuslab/FLYP#10]
https://github.com/locuslab/FLYP/tree/main#transfer-learning-on-stanfordcars

Running this code throws AssertionError: please specify correct k. 

How to handle this ?

**Comment by Bala93** [comment]
I guess, the file name should be src/main.py instead of main/few_shot.py ?

**Comment by Bala93** [comment]
I think, the same also applies in the case of caltech dataset. Also, there is a mistake in the input to the template parameter of stanford dataset. It should be stanfordcars_template, not stan**d**fordcars_template.

**Comment by SachinG007** [comment]
Hi @Bala93,
Yes, thanks for pointing out these typos. We have fixed them.
