### ISSUE TITLE
memory cost

### ISSUE THREAD

**Issue by VLadImirluren** [locuslab/FLYP#14]
Thanks for your nice work !
May I ask how much video memory is required?
Best wish~

**Comment by SachinG007** [comment]
Thanks for your interest in our work.
I am not sure what do you mean by "video" memory, but if you are referring to GPU memory, it totally depends on the batch size you use. For ImageNet experiments, with batch size of 512 on ViTB-B-16, it might require 3 A*6000 GPUs.

**Comment by VLadImirluren** [comment]
> Thanks for your interest in our work. I am not sure what do you mean by "video" memory, but if you are referring to GPU memory, it totally depends on the batch size you use. For ImageNet experiments, with batch size of 512 on ViTB-B-16, it might require 3 A*6000 GPUs.

sorry for my mistake.It actually is GPU memory I mean.
Thanks you~
Best wish~
