### ISSUE TITLE
How to load created checkpoints?

### ISSUE THREAD

**Issue by ugsup** [locuslab/FLYP#16]
How can I load the checkpoints that were saved during the training? I can't open the checkpoint.pt file with torch.load.

**Comment by wendioooo** [comment]
How did you load it? I have similar problem.

**Comment by ugsup** [comment]
There is a tag in the method create_model_and_transform() (https://github.com/locuslab/FLYP/blob/main/src/models/modeling.py), which is used in the CLIPEncoder(), where you can specify a tag. In order to use my own checkpoints, I have created a new entry in the list at the corresponding position of open_clip with the path to my own checkpoint. You may have to modify the method in open_clip if you are using local checkpoints.

**Comment by ugsup** [comment]
The torch_load() and torch_save() methods(https://github.com/locuslab/FLYP/blob/main/src/models/utils.py) here use the pickle library, but for some unknown reason this does not work. So instead of pickle.dumb() and pickle.load() I simply used the load and save methods of pytorch.
