### ISSUE TITLE
Regarding test evaluation in LP

### ISSUE THREAD

**Issue by Bala93** [locuslab/FLYP#17]
https://github.com/locuslab/FLYP/blob/215d5bb6feeda6675f60e5818abcb4f6465c83af/src/models/linear_lbfgs.py#L124

Shouldn't this be args.eval_datasets[1] instead of args.eval_datasets[0] as we are dealing with test data assuming the argument inputs are "StanfordCarsVal,StanfordCarsTest"

**Comment by Bala93** [comment]
I guess, the idea would be to find the optimal parameters through the use of the validation data, and get the metrics on the test data.

**Comment by SachinG007** [comment]
Yes, first get the best set of hparams through the val data and then use similar code to evaluate on test using the best hparams (the code might have to be updated a bit for that, like replacing eval_dataset[0] with [1] ).

**Comment by Bala93** [comment]
Yeah did that. Thanks.
