### ISSUE TITLE
ImageNet few-shot experiments

### ISSUE THREAD

**Issue by sinahmr** [locuslab/FLYP#20]
Hi,

Thank you for your great work. I'm trying to replicate few-shot ImageNet experiments, but I encounter some problems.

When I run `few_shot.py`, it gets stuck [in this while loop](https://github.com/locuslab/FLYP/blob/215d5bb6feeda6675f60e5818abcb4f6465c83af/src/models/flyp_loss_few_shot.py#L59). `len(texts1)` reaches `args.k` after a few iterations, but `len(texts0)` remains 1.
I'm running the script with these arguments (among others): `--train-dataset=ImageNet --eval-datasets=ImageNet,ImageNetV2,ImageNetR,ImageNetA,ImageNetSketch --ft_data="./datasets/csv/imagenet.csv" --k=4`

A similar infinite loop exists for the validation dataset as well, [in this line](https://github.com/locuslab/FLYP/blob/215d5bb6feeda6675f60e5818abcb4f6465c83af/src/models/flyp_loss_few_shot.py#L104), not sure if this one is also problematic.

Besides, I'm curios what dataset name should I add to the list of `eval-datasets` so that [this assert](https://github.com/locuslab/FLYP/blob/215d5bb6feeda6675f60e5818abcb4f6465c83af/src/models/flyp_loss_few_shot.py#L87) can be passed. As far as I'm concerned, there is no vanilla ImageNet dataset declared in `src/datasets/imagenet.py` that contains the string 'Val' in its name. (The same for 'Test' [here](https://github.com/locuslab/FLYP/blob/215d5bb6feeda6675f60e5818abcb4f6465c83af/src/models/flyp_loss_few_shot.py#L214))

Thank you.

**Comment by SachinG007** [comment]
I give --eval-datasets=ImageNet,ImageNetV2,ImageNetR,ImageNetA,ImageNetSketch,ObjectNet as the eval datasets for ImageNet experiments. The script pushed above for fewshot experiments was updated for experiments on SST2 and others. You can remove that assert for purpose of experimenting on ImageNet.
