### ISSUE TITLE
How to run few-shot on imagenet?

### ISSUE THREAD

**Issue by bangann** [locuslab/FLYP#6]
Hi,

Thank you for the great work! I'm trying to replicate your results on ImageNet under the few-shot setting, but couldn't find the running script. Could you please share the running script with me? Thank you!

**Comment by SachinG007** [comment]
The code for that will be the same as the full-shot finetuning, however you will have to create few-shot dataset from your full-shot ImageNet data. 
I would suggest you to run the code on around 50 random samples of fewshot training data (say 16). For validation too, you can sample a disjoint set from the training data if you want to early stop.

**Comment by bangann** [comment]
Thank you so much! So I just need to set  --train-dataset=ImageNet16, and use the full-shot fine-tuning script to run 50 times, would that be fine?

**Comment by SachinG007** [comment]
That's correct, however you will need to create the simlinks accordingly based on whatever train-dataset argument you share.
