### ISSUE TITLE
How to train on multi gpus?

### ISSUE THREAD

**Issue by 1359347500cwc** [locuslab/FLYP#8]
when i run this code in this command
```
export PYTHONPATH="$PYTHONPATH:$PWD"
srun --partition=atshare_a100_40g --kill-on-bad-exit=1 -n1 --gres=gpu:4 --ntasks-per-node=1 --quotatype=auto --mpi=pmi2 --cpus-per-task=32 \
    python -m torch.distributed.launch --master_port 12312 --nproc_per_node=4 src/main.py \
   --train-dataset=ImageNet \
   --epochs=10 --lr=1e-5 --wd=0.1 \
   --batch-size=128 \
   --model=/mnt/lustrenew/chenwenchao/code/CLIP-main/ckpt/ViT-B-16.pt \
   --eval-datasets=ImageNet \
   --template=openai_imagenet_template \
   --save=./checkpoints/ \
   --data-location=/mnt/cache/share/images/ \
   --ft_data="./datasets/csv/imagenet.csv" \
   --csv-img-key filepath \
   --csv-caption-key title \
   --exp_name=ImageNet/flyp_loss \
```
the effect batchsize is not change.
actually it shoud be (gpu * batchsize)  which means the batchsize is 4 * 128.
but it doesn't change.

**Comment by qlOvQlp** [comment]
may be you have launched 4 dp training tasks, the default training method is dp not ddp
`    model = torch.nn.DataParallel(model, device_ids=devices)` 
in flyp_loss.py 53 line

**Comment by qlOvQlp** [comment]
may be you have launched 4 DP tasks, the default training method used in FLYP is DP rather than DDP.
https://github.com/locuslab/FLYP/blob/d42180645e31c16c50a7b111410c98616c2c2872/src/models/flyp_loss.py#L53

**Comment by qlOvQlp** [comment]
> when i run this code in this command
> 
> ```
> export PYTHONPATH="$PYTHONPATH:$PWD"
> srun --partition=atshare_a100_40g --kill-on-bad-exit=1 -n1 --gres=gpu:4 --ntasks-per-node=1 --quotatype=auto --mpi=pmi2 --cpus-per-task=32 \
>     python -m torch.distributed.launch --master_port 12312 --nproc_per_node=4 src/main.py \
>    --train-dataset=ImageNet \
>    --epochs=10 --lr=1e-5 --wd=0.1 \
>    --batch-size=128 \
>    --model=/mnt/lustrenew/chenwenchao/code/CLIP-main/ckpt/ViT-B-16.pt \
>    --eval-datasets=ImageNet \
>    --template=openai_imagenet_template \
>    --save=./checkpoints/ \
>    --data-location=/mnt/cache/share/images/ \
>    --ft_data="./datasets/csv/imagenet.csv" \
>    --csv-img-key filepath \
>    --csv-caption-key title \
>    --exp_name=ImageNet/flyp_loss \
> ```
> 
> the effect batchsize is not change. actually it shoud be (gpu * batchsize) which means the batchsize is 4 * 128. but it doesn't change.

may be you have launched 4 DP tasks, the default training method used in FLYP is DP rather than DDP.
https://github.com/locuslab/FLYP/blob/d42180645e31c16c50a7b111410c98616c2c2872/src/models/flyp_loss.py#L53

**Comment by 1359347500cwc** [comment]
Thanks for your reply :), I think i have solved it.

**Comment by 1359347500cwc** [comment]
> > when i run this code in this command
> > ```
> > export PYTHONPATH="$PYTHONPATH:$PWD"
> > srun --partition=atshare_a100_40g --kill-on-bad-exit=1 -n1 --gres=gpu:4 --ntasks-per-node=1 --quotatype=auto --mpi=pmi2 --cpus-per-task=32 \
> >     python -m torch.distributed.launch --master_port 12312 --nproc_per_node=4 src/main.py \
> >    --train-dataset=ImageNet \
> >    --epochs=10 --lr=1e-5 --wd=0.1 \
> >    --batch-size=128 \
> >    --model=/mnt/lustrenew/chenwenchao/code/CLIP-main/ckpt/ViT-B-16.pt \
> >    --eval-datasets=ImageNet \
> >    --template=openai_imagenet_template \
> >    --save=./checkpoints/ \
> >    --data-location=/mnt/cache/share/images/ \
> >    --ft_data="./datasets/csv/imagenet.csv" \
> >    --csv-img-key filepath \
> >    --csv-caption-key title \
> >    --exp_name=ImageNet/flyp_loss \
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the effect batchsize is not change. actually it shoud be (gpu * batchsize) which means the batchsize is 4 * 128. but it doesn't change.
> 
> may be you have launched 4 DP tasks, the default training method used in FLYP is DP rather than DDP.
> 
> https://github.com/locuslab/FLYP/blob/d42180645e31c16c50a7b111410c98616c2c2872/src/models/flyp_loss.py#L53

thanks for your reply :). I have solved it.
