### ISSUE TITLE
How to split the datasets into train, val and test

### ISSUE THREAD

**Issue by LixDemon** [locuslab/FLYP#9]
How Caltech, Cars and Flowers are split into train, val and test? Can you provide some instructions or codes for that? Thanks!

**Comment by SachinG007** [comment]
Hi @LixDemon ,
Thanks for your interest in our work. 

1) For the flowers dataset: we use the official training, validation and test split as provided in the dataset (setid.mat file gives the split id's). Data link: https://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html

2) For caltech, we split into train val and test in 60:20:20 ratio.

3) For Stanford Cars, we split the training dataset in 80:20 ratio to get the train val split. 

Let us know if something is unclear; we would be happy to help.

Thanks

**Comment by Bala93** [comment]
Can you provide the csv files being created after the train, valid, and test split. It will be useful in getting consistenct results. Thanks for your time.

**Comment by LixDemon** [comment]
Any code for splitting the dataset? I see some .py files in your DATA.md, which is absent in your code files.

**Comment by Bala93** [comment]
Hi @LixDemon. For now, I am using this module (https://pypi.org/project/split-folders/) to split the folders for train, valid, and test.

**Comment by SachinG007** [comment]
Hi @Bala93 @LixDemon,
We have added the csv files for train/val/test split for Caltech and train/val split for cars here based on your request: https://github.com/locuslab/FLYP/tree/main/datacreation_scripts/sample_csv.

I hope this helps you to create a similar split. Let me know if we can be of more help.

**Comment by SachinG007** [comment]
Hi @LixDemon ,
I added train val split code which I used here: https://github.com/locuslab/FLYP/blob/main/datacreation_scripts/traintestsplit.py.
